# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbc < Formula
  desc "Database Connect"
  homepage "https://github.com/birdicare/homebrew-dbc"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.6.1/birdiecare_dbc_0.6.1_darwin_arm64.tar.gz"
      sha256 "c8ce31a67d02512f6fc72a917c3fad555415565c837af760c88a8c623023d08d"

      def install
        bin.install "dbc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.6.1/birdiecare_dbc_0.6.1_darwin_amd64.tar.gz"
      sha256 "92c1957003afd445b8dc1dd3ec46f896bd2055fca724180795d98f52560d7df7"

      def install
        bin.install "dbc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.6.1/birdiecare_dbc_0.6.1_linux_amd64.tar.gz"
      sha256 "591820586d1cb115a24d4ecbca1fc2331c3be70a47d7565187796b6873091844"

      def install
        bin.install "dbc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.6.1/birdiecare_dbc_0.6.1_linux_arm64.tar.gz"
      sha256 "9be7354524ccb6a0c70edcf7528ebb93611a9a90f580a580bfe6e8df01987149"

      def install
        bin.install "dbc"
      end
    end
  end
end
